name: Create and push Docker image

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs: 
    build_and_push_image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
          - name: Checkout reposity
            uses: actions/checkout@v4

          - name: Log into Container Registry
            uses: docker/login-action@v3
            with:
                 registry: ${{ env.REGISTRY }}
                 username: ${{ github.actor }}
                 password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract meta data(tags,labels)from Dockerfile
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
              
          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              platforms: linux/arm/v6,linux/arm/v7,linux/amd64,linux/arm64
              file: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.tags }}